// <auto-generated />
namespace ArtGallery_ECommerce.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class fixedspellingerrorincreaterolls : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fixedspellingerrorincreaterolls));
        
        string IMigrationMetadata.Id
        {
            get { return "201807280418277_fixed spelling error in createrolls()"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
